import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tkinter import messagebox


# Draws the different class points and the regions of each class according to the model's predictions.
def visualize_model():
    print("To be implemented")

# Computes confusion matrix in addition to accuracy, recall and precision (on 3 classes rather than 2)
def compute_confusion_matrix(y, y_pred):
    print("To be implemented")




